### ISSUE TITLE
/cshop add name command not working

### ISSUE THREAD

**Issue by servantthought** [BoxOfDevs/CommandShop#12] opened 2018-03-14 08:26 UTC
### Brief description

Everyone I type /cshop add anyname any command
I get "An unknown error occurred while attempting to perform this command"

### Steps to reproduce

1. .../cshop add spawn spawn
2. ...
3. ...

### Expected result
 fix the plugin
![screenshot_20180314-042223](https://user-images.githubusercontent.com/36419915/37390859-c721f47c-273f-11e8-95df-dc982d3ba22a.png)
![screenshot_20180314-042232](https://user-images.githubusercontent.com/36419915/37390873-d06dcdee-273f-11e8-938b-c3b77ed277f4.png)

### Server Information
* CommandShop Version: 
* Software Version: 
* Server OS: 

### CrashDumps/Errors
```
14.03 09:13:51 [Server] Server thread/INFO [Broadcaster] Report Hackers and trouble makers 
14.03 09:13:11 [Server] Server thread/DEBUG #25 /jar/PocketMine-1.2.10-dev.phar(1): require(string phar:///jar/PocketMine-1.2.10-dev.phar/src/pocketmine/PocketMine.php) 
14.03 09:13:11 [Server] Server thread/DEBUG #24 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/) 
14.03 09:13:11 [Server] Server thread/DEBUG #23 src/pocketmine/Server(1744): pocketmine\Server->start() 
14.03 09:13:11 [Server] Server thread/DEBUG #22 src/pocketmine/Server(2158): pocketmine\Server->tickProcessor() 
14.03 09:13:11 [Server] Server thread/DEBUG #21 src/pocketmine/Server(2283): pocketmine\Server->tick() 
14.03 09:13:11 [Server] Server thread/DEBUG #20 src/pocketmine/Server(2531): pocketmine\network\Network->processInterfaces() 
14.03 09:13:11 [Server] Server thread/DEBUG #19 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process() 
14.03 09:13:11 [Server] Server thread/DEBUG #18 src/pocketmine/network/mcpe/RakLibInterface(88): raklib\server\ServerHandler->handlePacket() 
14.03 09:13:11 [Server] Server thread/DEBUG #17 vendor/pocketmine/raklib/server/ServerHandler(103): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 174.232.7.160 8888, raklib\protocol\EncapsulatedPacket object, integer 0) 
14.03 09:13:11 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/RakLibInterface(149): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object) 
14.03 09:13:11 [Server] Server thread/DEBUG #15 src/pocketmine/Player(2964): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object) 
14.03 09:13:11 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object) 
14.03 09:13:11 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object) 
14.03 09:13:11 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object) 
14.03 09:13:11 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object) 
14.03 09:13:11 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(220): pocketmine\Player->chat(string /cshop add spawn spawn) 
14.03 09:13:11 [Server] Server thread/DEBUG #9 src/pocketmine/Player(2117): pocketmine\Server->dispatchCommand(pocketmine\Player object, string cshop add spawn spawn) 
14.03 09:13:11 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1989): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string cshop add spawn spawn) 
14.03 09:13:11 [Server] Server thread/DEBUG #7 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string cshop, array Array()) 
14.03 09:13:11 [Server] Server thread/DEBUG #6 src/pocketmine/command/PluginCommand(58): BoxOfDevs\CommandShop\CommandShop->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string cshop, array Array()) 
14.03 09:13:11 [Server] Server thread/DEBUG #5 CommandShop_v1.0.0.phar/src/BoxOfDevs/CommandShop/CommandShop(238): pocketmine\plugin\PluginBase->getConfig() 
14.03 09:13:11 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginBase(244): pocketmine\plugin\PluginBase->reloadConfig() 
14.03 09:13:11 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginBase(264): pocketmine\utils\Config->__construct(string /plugins/CommandShop/config.yml) 
14.03 09:13:11 [Server] Server thread/DEBUG #2 src/pocketmine/utils/Config(86): pocketmine\utils\Config->load(string /plugins/CommandShop/config.yml, integer -1, array Array()) 
14.03 09:13:11 [Server] Server thread/DEBUG #1 src/pocketmine/utils/Config(155): yaml_parse(string ---..buy.money.success: '{prefix}You successfully bought the command {cmd} for {amount}.. {unit}!{line}{prefix}The command has already been executed.'..buy.money.miss: '{error}You don''t have enough money to buy this command. You would.. need {amount} {unit}!'..buy.item.success: '{prefix}You successfully bought the command {cmd} with the item.. {item}!{line}{prefix}The command has already been executed.'..buy.item.miss: '{error}You don''t have enough items to buy this command, items needed:{line}Item:.. {item} Amount: {amount}'..buy.contactadmin: '{line}If you are a normal user, please contact your server administrator!'..command.notfound: '{error}Command {cmd} wasn''t found in the list of buyable commands!'..sign.confirm: '{prefix}Tap the sign again to confirm that you want to buy the command.. {cmd}!'..sign.noperm: '{error}You don''t have the permission to buy commands via signs!'..sign.nobreak: '{error}You don''t have the permission to break CommandShop signs!'..buycmd.disabled: '{error}/buycmd is disabled for this buyable command!'..commands:.. example:.. cmds:.. - tp {player} 123 123 123.. buycmd: "true".. price:.. paytype: item.. item: 1:0:64.. demon:.. cmds:.. - kit demon.. buycmd: "true".. price:5000.. paytype: item.. item: 259:0:1.......) 
14.03 09:13:11 [Server] Server thread/DEBUG #0 (): pocketmine\error_handler(integer 2, string yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 30, column 14), context while scanning a simple key (line 29, column 5), string phar:///jar/PocketMine-1.2.10-dev.phar/src/pocketmine/utils/Config.php, integer 155, array Array()) 
14.03 09:13:11 [Server] Server thread/CRITICAL ErrorException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 30, column 14), context while scanning a simple key (line 29, column 5)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 155
14.03 09:13:11 [Server] Server thread/CRITICAL Unhandled exception executing command 'cshop add spawn spawn' in cshop: yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 30, column 14), context while scanning a simple key (line 29, column 5)
```

**Comment by ghost** [comment] 2018-03-14 12:45
This issue appears to not be formatted correctly, please close this issue and provide the correct information such as reproduction steps (🤪 + 😼 = 👪), and crash dumps (🚚 + 💩 = ⚡️).

**Comment by servantthought** [comment] 2018-03-14 16:17
There I updated the crash info
.... Sorry for the delay

**Comment by HimbeersaftLP** [comment] 2018-03-14 18:15
This seems to be an issue with your config.yml, did you ever change anything in it? And can you send it too?

**Comment by servantthought** [comment] 2018-03-15 00:29
I never changed it only downloaded it from here...

**Comment by servantthought** [comment] 2018-03-15 00:38
I never edit the file... 
I downloaded my server phar
And used unphar.com
[73-CommandShop_v1-734c2.zip](https://github.com/BoxOfDevs/CommandShop/files/1813608/73-CommandShop_v1-734c2.zip)

**Comment by servantthought** [comment] 2018-03-15 00:46
Yes I can send file... I never changed the config
.. I got the files from github

**Comment by HimbeersaftLP** [comment] 2018-08-17 07:26
Has this fixed itself already?

**Comment by HimbeersaftLP** [comment] 2020-04-06 15:34
I can't reproduce this anymore

**Closed as completed by HimbeersaftLP** 2020-04-06 15:34 UTC
Labels: Can't reproduce
